/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// This file is @generated by gen_fwd.py
// Do not edit this file directly, instead update gen_fwd_input.toml and run:
// buck run @arvr/mode/platform010/opt //arvr/libraries/momentum:gen_fwd

#pragma once

#include <memory>

namespace momentum {

struct MultiposeSolverOptions;

using MultiposeSolverOptions_p = ::std::shared_ptr<MultiposeSolverOptions>;
using MultiposeSolverOptions_u = ::std::unique_ptr<MultiposeSolverOptions>;
using MultiposeSolverOptions_w = ::std::weak_ptr<MultiposeSolverOptions>;
using MultiposeSolverOptions_const_p = ::std::shared_ptr<const MultiposeSolverOptions>;
using MultiposeSolverOptions_const_u = ::std::unique_ptr<const MultiposeSolverOptions>;
using MultiposeSolverOptions_const_w = ::std::weak_ptr<const MultiposeSolverOptions>;

struct SequenceCholeskySolverOptions;

using SequenceCholeskySolverOptions_p = ::std::shared_ptr<SequenceCholeskySolverOptions>;
using SequenceCholeskySolverOptions_u = ::std::unique_ptr<SequenceCholeskySolverOptions>;
using SequenceCholeskySolverOptions_w = ::std::weak_ptr<SequenceCholeskySolverOptions>;
using SequenceCholeskySolverOptions_const_p =
    ::std::shared_ptr<const SequenceCholeskySolverOptions>;
using SequenceCholeskySolverOptions_const_u =
    ::std::unique_ptr<const SequenceCholeskySolverOptions>;
using SequenceCholeskySolverOptions_const_w = ::std::weak_ptr<const SequenceCholeskySolverOptions>;

struct SequenceSolverOptionsBase;

using SequenceSolverOptionsBase_p = ::std::shared_ptr<SequenceSolverOptionsBase>;
using SequenceSolverOptionsBase_u = ::std::unique_ptr<SequenceSolverOptionsBase>;
using SequenceSolverOptionsBase_w = ::std::weak_ptr<SequenceSolverOptionsBase>;
using SequenceSolverOptionsBase_const_p = ::std::shared_ptr<const SequenceSolverOptionsBase>;
using SequenceSolverOptionsBase_const_u = ::std::unique_ptr<const SequenceSolverOptionsBase>;
using SequenceSolverOptionsBase_const_w = ::std::weak_ptr<const SequenceSolverOptionsBase>;

struct SequenceSolverOptions;

using SequenceSolverOptions_p = ::std::shared_ptr<SequenceSolverOptions>;
using SequenceSolverOptions_u = ::std::unique_ptr<SequenceSolverOptions>;
using SequenceSolverOptions_w = ::std::weak_ptr<SequenceSolverOptions>;
using SequenceSolverOptions_const_p = ::std::shared_ptr<const SequenceSolverOptions>;
using SequenceSolverOptions_const_u = ::std::unique_ptr<const SequenceSolverOptions>;
using SequenceSolverOptions_const_w = ::std::weak_ptr<const SequenceSolverOptions>;

template <typename T>
struct JointToJointSequenceConstraintT;
using JointToJointSequenceConstraint = JointToJointSequenceConstraintT<float>;
using JointToJointSequenceConstraintd = JointToJointSequenceConstraintT<double>;

using JointToJointSequenceConstraint_p = ::std::shared_ptr<JointToJointSequenceConstraint>;
using JointToJointSequenceConstraint_u = ::std::unique_ptr<JointToJointSequenceConstraint>;
using JointToJointSequenceConstraint_w = ::std::weak_ptr<JointToJointSequenceConstraint>;
using JointToJointSequenceConstraint_const_p =
    ::std::shared_ptr<const JointToJointSequenceConstraint>;
using JointToJointSequenceConstraint_const_u =
    ::std::unique_ptr<const JointToJointSequenceConstraint>;
using JointToJointSequenceConstraint_const_w =
    ::std::weak_ptr<const JointToJointSequenceConstraint>;

using JointToJointSequenceConstraintd_p = ::std::shared_ptr<JointToJointSequenceConstraintd>;
using JointToJointSequenceConstraintd_u = ::std::unique_ptr<JointToJointSequenceConstraintd>;
using JointToJointSequenceConstraintd_w = ::std::weak_ptr<JointToJointSequenceConstraintd>;
using JointToJointSequenceConstraintd_const_p =
    ::std::shared_ptr<const JointToJointSequenceConstraintd>;
using JointToJointSequenceConstraintd_const_u =
    ::std::unique_ptr<const JointToJointSequenceConstraintd>;
using JointToJointSequenceConstraintd_const_w =
    ::std::weak_ptr<const JointToJointSequenceConstraintd>;

template <typename T>
class AccelerationSequenceErrorFunctionT;
using AccelerationSequenceErrorFunction = AccelerationSequenceErrorFunctionT<float>;
using AccelerationSequenceErrorFunctiond = AccelerationSequenceErrorFunctionT<double>;

using AccelerationSequenceErrorFunction_p = ::std::shared_ptr<AccelerationSequenceErrorFunction>;
using AccelerationSequenceErrorFunction_u = ::std::unique_ptr<AccelerationSequenceErrorFunction>;
using AccelerationSequenceErrorFunction_w = ::std::weak_ptr<AccelerationSequenceErrorFunction>;
using AccelerationSequenceErrorFunction_const_p =
    ::std::shared_ptr<const AccelerationSequenceErrorFunction>;
using AccelerationSequenceErrorFunction_const_u =
    ::std::unique_ptr<const AccelerationSequenceErrorFunction>;
using AccelerationSequenceErrorFunction_const_w =
    ::std::weak_ptr<const AccelerationSequenceErrorFunction>;

using AccelerationSequenceErrorFunctiond_p = ::std::shared_ptr<AccelerationSequenceErrorFunctiond>;
using AccelerationSequenceErrorFunctiond_u = ::std::unique_ptr<AccelerationSequenceErrorFunctiond>;
using AccelerationSequenceErrorFunctiond_w = ::std::weak_ptr<AccelerationSequenceErrorFunctiond>;
using AccelerationSequenceErrorFunctiond_const_p =
    ::std::shared_ptr<const AccelerationSequenceErrorFunctiond>;
using AccelerationSequenceErrorFunctiond_const_u =
    ::std::unique_ptr<const AccelerationSequenceErrorFunctiond>;
using AccelerationSequenceErrorFunctiond_const_w =
    ::std::weak_ptr<const AccelerationSequenceErrorFunctiond>;

template <typename T>
class FiniteDifferenceSequenceErrorFunctionT;
using FiniteDifferenceSequenceErrorFunction = FiniteDifferenceSequenceErrorFunctionT<float>;
using FiniteDifferenceSequenceErrorFunctiond = FiniteDifferenceSequenceErrorFunctionT<double>;

using FiniteDifferenceSequenceErrorFunction_p =
    ::std::shared_ptr<FiniteDifferenceSequenceErrorFunction>;
using FiniteDifferenceSequenceErrorFunction_u =
    ::std::unique_ptr<FiniteDifferenceSequenceErrorFunction>;
using FiniteDifferenceSequenceErrorFunction_w =
    ::std::weak_ptr<FiniteDifferenceSequenceErrorFunction>;
using FiniteDifferenceSequenceErrorFunction_const_p =
    ::std::shared_ptr<const FiniteDifferenceSequenceErrorFunction>;
using FiniteDifferenceSequenceErrorFunction_const_u =
    ::std::unique_ptr<const FiniteDifferenceSequenceErrorFunction>;
using FiniteDifferenceSequenceErrorFunction_const_w =
    ::std::weak_ptr<const FiniteDifferenceSequenceErrorFunction>;

using FiniteDifferenceSequenceErrorFunctiond_p =
    ::std::shared_ptr<FiniteDifferenceSequenceErrorFunctiond>;
using FiniteDifferenceSequenceErrorFunctiond_u =
    ::std::unique_ptr<FiniteDifferenceSequenceErrorFunctiond>;
using FiniteDifferenceSequenceErrorFunctiond_w =
    ::std::weak_ptr<FiniteDifferenceSequenceErrorFunctiond>;
using FiniteDifferenceSequenceErrorFunctiond_const_p =
    ::std::shared_ptr<const FiniteDifferenceSequenceErrorFunctiond>;
using FiniteDifferenceSequenceErrorFunctiond_const_u =
    ::std::unique_ptr<const FiniteDifferenceSequenceErrorFunctiond>;
using FiniteDifferenceSequenceErrorFunctiond_const_w =
    ::std::weak_ptr<const FiniteDifferenceSequenceErrorFunctiond>;

template <typename T>
class JerkSequenceErrorFunctionT;
using JerkSequenceErrorFunction = JerkSequenceErrorFunctionT<float>;
using JerkSequenceErrorFunctiond = JerkSequenceErrorFunctionT<double>;

using JerkSequenceErrorFunction_p = ::std::shared_ptr<JerkSequenceErrorFunction>;
using JerkSequenceErrorFunction_u = ::std::unique_ptr<JerkSequenceErrorFunction>;
using JerkSequenceErrorFunction_w = ::std::weak_ptr<JerkSequenceErrorFunction>;
using JerkSequenceErrorFunction_const_p = ::std::shared_ptr<const JerkSequenceErrorFunction>;
using JerkSequenceErrorFunction_const_u = ::std::unique_ptr<const JerkSequenceErrorFunction>;
using JerkSequenceErrorFunction_const_w = ::std::weak_ptr<const JerkSequenceErrorFunction>;

using JerkSequenceErrorFunctiond_p = ::std::shared_ptr<JerkSequenceErrorFunctiond>;
using JerkSequenceErrorFunctiond_u = ::std::unique_ptr<JerkSequenceErrorFunctiond>;
using JerkSequenceErrorFunctiond_w = ::std::weak_ptr<JerkSequenceErrorFunctiond>;
using JerkSequenceErrorFunctiond_const_p = ::std::shared_ptr<const JerkSequenceErrorFunctiond>;
using JerkSequenceErrorFunctiond_const_u = ::std::unique_ptr<const JerkSequenceErrorFunctiond>;
using JerkSequenceErrorFunctiond_const_w = ::std::weak_ptr<const JerkSequenceErrorFunctiond>;

template <typename T>
class JointToJointSequenceErrorFunctionT;
using JointToJointSequenceErrorFunction = JointToJointSequenceErrorFunctionT<float>;
using JointToJointSequenceErrorFunctiond = JointToJointSequenceErrorFunctionT<double>;

using JointToJointSequenceErrorFunction_p = ::std::shared_ptr<JointToJointSequenceErrorFunction>;
using JointToJointSequenceErrorFunction_u = ::std::unique_ptr<JointToJointSequenceErrorFunction>;
using JointToJointSequenceErrorFunction_w = ::std::weak_ptr<JointToJointSequenceErrorFunction>;
using JointToJointSequenceErrorFunction_const_p =
    ::std::shared_ptr<const JointToJointSequenceErrorFunction>;
using JointToJointSequenceErrorFunction_const_u =
    ::std::unique_ptr<const JointToJointSequenceErrorFunction>;
using JointToJointSequenceErrorFunction_const_w =
    ::std::weak_ptr<const JointToJointSequenceErrorFunction>;

using JointToJointSequenceErrorFunctiond_p = ::std::shared_ptr<JointToJointSequenceErrorFunctiond>;
using JointToJointSequenceErrorFunctiond_u = ::std::unique_ptr<JointToJointSequenceErrorFunctiond>;
using JointToJointSequenceErrorFunctiond_w = ::std::weak_ptr<JointToJointSequenceErrorFunctiond>;
using JointToJointSequenceErrorFunctiond_const_p =
    ::std::shared_ptr<const JointToJointSequenceErrorFunctiond>;
using JointToJointSequenceErrorFunctiond_const_u =
    ::std::unique_ptr<const JointToJointSequenceErrorFunctiond>;
using JointToJointSequenceErrorFunctiond_const_w =
    ::std::weak_ptr<const JointToJointSequenceErrorFunctiond>;

template <typename T>
class SequenceErrorFunctionT;
using SequenceErrorFunction = SequenceErrorFunctionT<float>;
using SequenceErrorFunctiond = SequenceErrorFunctionT<double>;

using SequenceErrorFunction_p = ::std::shared_ptr<SequenceErrorFunction>;
using SequenceErrorFunction_u = ::std::unique_ptr<SequenceErrorFunction>;
using SequenceErrorFunction_w = ::std::weak_ptr<SequenceErrorFunction>;
using SequenceErrorFunction_const_p = ::std::shared_ptr<const SequenceErrorFunction>;
using SequenceErrorFunction_const_u = ::std::unique_ptr<const SequenceErrorFunction>;
using SequenceErrorFunction_const_w = ::std::weak_ptr<const SequenceErrorFunction>;

using SequenceErrorFunctiond_p = ::std::shared_ptr<SequenceErrorFunctiond>;
using SequenceErrorFunctiond_u = ::std::unique_ptr<SequenceErrorFunctiond>;
using SequenceErrorFunctiond_w = ::std::weak_ptr<SequenceErrorFunctiond>;
using SequenceErrorFunctiond_const_p = ::std::shared_ptr<const SequenceErrorFunctiond>;
using SequenceErrorFunctiond_const_u = ::std::unique_ptr<const SequenceErrorFunctiond>;
using SequenceErrorFunctiond_const_w = ::std::weak_ptr<const SequenceErrorFunctiond>;

template <typename T>
class ModelParametersSequenceErrorFunctionT;
using ModelParametersSequenceErrorFunction = ModelParametersSequenceErrorFunctionT<float>;
using ModelParametersSequenceErrorFunctiond = ModelParametersSequenceErrorFunctionT<double>;

using ModelParametersSequenceErrorFunction_p =
    ::std::shared_ptr<ModelParametersSequenceErrorFunction>;
using ModelParametersSequenceErrorFunction_u =
    ::std::unique_ptr<ModelParametersSequenceErrorFunction>;
using ModelParametersSequenceErrorFunction_w =
    ::std::weak_ptr<ModelParametersSequenceErrorFunction>;
using ModelParametersSequenceErrorFunction_const_p =
    ::std::shared_ptr<const ModelParametersSequenceErrorFunction>;
using ModelParametersSequenceErrorFunction_const_u =
    ::std::unique_ptr<const ModelParametersSequenceErrorFunction>;
using ModelParametersSequenceErrorFunction_const_w =
    ::std::weak_ptr<const ModelParametersSequenceErrorFunction>;

using ModelParametersSequenceErrorFunctiond_p =
    ::std::shared_ptr<ModelParametersSequenceErrorFunctiond>;
using ModelParametersSequenceErrorFunctiond_u =
    ::std::unique_ptr<ModelParametersSequenceErrorFunctiond>;
using ModelParametersSequenceErrorFunctiond_w =
    ::std::weak_ptr<ModelParametersSequenceErrorFunctiond>;
using ModelParametersSequenceErrorFunctiond_const_p =
    ::std::shared_ptr<const ModelParametersSequenceErrorFunctiond>;
using ModelParametersSequenceErrorFunctiond_const_u =
    ::std::unique_ptr<const ModelParametersSequenceErrorFunctiond>;
using ModelParametersSequenceErrorFunctiond_const_w =
    ::std::weak_ptr<const ModelParametersSequenceErrorFunctiond>;

template <typename T>
class MultiposeSolverT;
using MultiposeSolver = MultiposeSolverT<float>;
using MultiposeSolverd = MultiposeSolverT<double>;

using MultiposeSolver_p = ::std::shared_ptr<MultiposeSolver>;
using MultiposeSolver_u = ::std::unique_ptr<MultiposeSolver>;
using MultiposeSolver_w = ::std::weak_ptr<MultiposeSolver>;
using MultiposeSolver_const_p = ::std::shared_ptr<const MultiposeSolver>;
using MultiposeSolver_const_u = ::std::unique_ptr<const MultiposeSolver>;
using MultiposeSolver_const_w = ::std::weak_ptr<const MultiposeSolver>;

using MultiposeSolverd_p = ::std::shared_ptr<MultiposeSolverd>;
using MultiposeSolverd_u = ::std::unique_ptr<MultiposeSolverd>;
using MultiposeSolverd_w = ::std::weak_ptr<MultiposeSolverd>;
using MultiposeSolverd_const_p = ::std::shared_ptr<const MultiposeSolverd>;
using MultiposeSolverd_const_u = ::std::unique_ptr<const MultiposeSolverd>;
using MultiposeSolverd_const_w = ::std::weak_ptr<const MultiposeSolverd>;

template <typename T>
class MultiposeSolverFunctionT;
using MultiposeSolverFunction = MultiposeSolverFunctionT<float>;
using MultiposeSolverFunctiond = MultiposeSolverFunctionT<double>;

using MultiposeSolverFunction_p = ::std::shared_ptr<MultiposeSolverFunction>;
using MultiposeSolverFunction_u = ::std::unique_ptr<MultiposeSolverFunction>;
using MultiposeSolverFunction_w = ::std::weak_ptr<MultiposeSolverFunction>;
using MultiposeSolverFunction_const_p = ::std::shared_ptr<const MultiposeSolverFunction>;
using MultiposeSolverFunction_const_u = ::std::unique_ptr<const MultiposeSolverFunction>;
using MultiposeSolverFunction_const_w = ::std::weak_ptr<const MultiposeSolverFunction>;

using MultiposeSolverFunctiond_p = ::std::shared_ptr<MultiposeSolverFunctiond>;
using MultiposeSolverFunctiond_u = ::std::unique_ptr<MultiposeSolverFunctiond>;
using MultiposeSolverFunctiond_w = ::std::weak_ptr<MultiposeSolverFunctiond>;
using MultiposeSolverFunctiond_const_p = ::std::shared_ptr<const MultiposeSolverFunctiond>;
using MultiposeSolverFunctiond_const_u = ::std::unique_ptr<const MultiposeSolverFunctiond>;
using MultiposeSolverFunctiond_const_w = ::std::weak_ptr<const MultiposeSolverFunctiond>;

template <typename T>
class SequenceCholeskySolverT;
using SequenceCholeskySolver = SequenceCholeskySolverT<float>;
using SequenceCholeskySolverd = SequenceCholeskySolverT<double>;

using SequenceCholeskySolver_p = ::std::shared_ptr<SequenceCholeskySolver>;
using SequenceCholeskySolver_u = ::std::unique_ptr<SequenceCholeskySolver>;
using SequenceCholeskySolver_w = ::std::weak_ptr<SequenceCholeskySolver>;
using SequenceCholeskySolver_const_p = ::std::shared_ptr<const SequenceCholeskySolver>;
using SequenceCholeskySolver_const_u = ::std::unique_ptr<const SequenceCholeskySolver>;
using SequenceCholeskySolver_const_w = ::std::weak_ptr<const SequenceCholeskySolver>;

using SequenceCholeskySolverd_p = ::std::shared_ptr<SequenceCholeskySolverd>;
using SequenceCholeskySolverd_u = ::std::unique_ptr<SequenceCholeskySolverd>;
using SequenceCholeskySolverd_w = ::std::weak_ptr<SequenceCholeskySolverd>;
using SequenceCholeskySolverd_const_p = ::std::shared_ptr<const SequenceCholeskySolverd>;
using SequenceCholeskySolverd_const_u = ::std::unique_ptr<const SequenceCholeskySolverd>;
using SequenceCholeskySolverd_const_w = ::std::weak_ptr<const SequenceCholeskySolverd>;

template <typename T>
class SequenceSolverBaseT;
using SequenceSolverBase = SequenceSolverBaseT<float>;
using SequenceSolverBased = SequenceSolverBaseT<double>;

using SequenceSolverBase_p = ::std::shared_ptr<SequenceSolverBase>;
using SequenceSolverBase_u = ::std::unique_ptr<SequenceSolverBase>;
using SequenceSolverBase_w = ::std::weak_ptr<SequenceSolverBase>;
using SequenceSolverBase_const_p = ::std::shared_ptr<const SequenceSolverBase>;
using SequenceSolverBase_const_u = ::std::unique_ptr<const SequenceSolverBase>;
using SequenceSolverBase_const_w = ::std::weak_ptr<const SequenceSolverBase>;

using SequenceSolverBased_p = ::std::shared_ptr<SequenceSolverBased>;
using SequenceSolverBased_u = ::std::unique_ptr<SequenceSolverBased>;
using SequenceSolverBased_w = ::std::weak_ptr<SequenceSolverBased>;
using SequenceSolverBased_const_p = ::std::shared_ptr<const SequenceSolverBased>;
using SequenceSolverBased_const_u = ::std::unique_ptr<const SequenceSolverBased>;
using SequenceSolverBased_const_w = ::std::weak_ptr<const SequenceSolverBased>;

template <typename T>
class SequenceSolverT;
using SequenceSolver = SequenceSolverT<float>;
using SequenceSolverd = SequenceSolverT<double>;

using SequenceSolver_p = ::std::shared_ptr<SequenceSolver>;
using SequenceSolver_u = ::std::unique_ptr<SequenceSolver>;
using SequenceSolver_w = ::std::weak_ptr<SequenceSolver>;
using SequenceSolver_const_p = ::std::shared_ptr<const SequenceSolver>;
using SequenceSolver_const_u = ::std::unique_ptr<const SequenceSolver>;
using SequenceSolver_const_w = ::std::weak_ptr<const SequenceSolver>;

using SequenceSolverd_p = ::std::shared_ptr<SequenceSolverd>;
using SequenceSolverd_u = ::std::unique_ptr<SequenceSolverd>;
using SequenceSolverd_w = ::std::weak_ptr<SequenceSolverd>;
using SequenceSolverd_const_p = ::std::shared_ptr<const SequenceSolverd>;
using SequenceSolverd_const_u = ::std::unique_ptr<const SequenceSolverd>;
using SequenceSolverd_const_w = ::std::weak_ptr<const SequenceSolverd>;

template <typename T>
class SequenceSolverFunctionT;
using SequenceSolverFunction = SequenceSolverFunctionT<float>;
using SequenceSolverFunctiond = SequenceSolverFunctionT<double>;

using SequenceSolverFunction_p = ::std::shared_ptr<SequenceSolverFunction>;
using SequenceSolverFunction_u = ::std::unique_ptr<SequenceSolverFunction>;
using SequenceSolverFunction_w = ::std::weak_ptr<SequenceSolverFunction>;
using SequenceSolverFunction_const_p = ::std::shared_ptr<const SequenceSolverFunction>;
using SequenceSolverFunction_const_u = ::std::unique_ptr<const SequenceSolverFunction>;
using SequenceSolverFunction_const_w = ::std::weak_ptr<const SequenceSolverFunction>;

using SequenceSolverFunctiond_p = ::std::shared_ptr<SequenceSolverFunctiond>;
using SequenceSolverFunctiond_u = ::std::unique_ptr<SequenceSolverFunctiond>;
using SequenceSolverFunctiond_w = ::std::weak_ptr<SequenceSolverFunctiond>;
using SequenceSolverFunctiond_const_p = ::std::shared_ptr<const SequenceSolverFunctiond>;
using SequenceSolverFunctiond_const_u = ::std::unique_ptr<const SequenceSolverFunctiond>;
using SequenceSolverFunctiond_const_w = ::std::weak_ptr<const SequenceSolverFunctiond>;

template <typename T>
class StateSequenceErrorFunctionT;
using StateSequenceErrorFunction = StateSequenceErrorFunctionT<float>;
using StateSequenceErrorFunctiond = StateSequenceErrorFunctionT<double>;

using StateSequenceErrorFunction_p = ::std::shared_ptr<StateSequenceErrorFunction>;
using StateSequenceErrorFunction_u = ::std::unique_ptr<StateSequenceErrorFunction>;
using StateSequenceErrorFunction_w = ::std::weak_ptr<StateSequenceErrorFunction>;
using StateSequenceErrorFunction_const_p = ::std::shared_ptr<const StateSequenceErrorFunction>;
using StateSequenceErrorFunction_const_u = ::std::unique_ptr<const StateSequenceErrorFunction>;
using StateSequenceErrorFunction_const_w = ::std::weak_ptr<const StateSequenceErrorFunction>;

using StateSequenceErrorFunctiond_p = ::std::shared_ptr<StateSequenceErrorFunctiond>;
using StateSequenceErrorFunctiond_u = ::std::unique_ptr<StateSequenceErrorFunctiond>;
using StateSequenceErrorFunctiond_w = ::std::weak_ptr<StateSequenceErrorFunctiond>;
using StateSequenceErrorFunctiond_const_p = ::std::shared_ptr<const StateSequenceErrorFunctiond>;
using StateSequenceErrorFunctiond_const_u = ::std::unique_ptr<const StateSequenceErrorFunctiond>;
using StateSequenceErrorFunctiond_const_w = ::std::weak_ptr<const StateSequenceErrorFunctiond>;

template <typename T>
class VelocityMagnitudeSequenceErrorFunctionT;
using VelocityMagnitudeSequenceErrorFunction = VelocityMagnitudeSequenceErrorFunctionT<float>;
using VelocityMagnitudeSequenceErrorFunctiond = VelocityMagnitudeSequenceErrorFunctionT<double>;

using VelocityMagnitudeSequenceErrorFunction_p =
    ::std::shared_ptr<VelocityMagnitudeSequenceErrorFunction>;
using VelocityMagnitudeSequenceErrorFunction_u =
    ::std::unique_ptr<VelocityMagnitudeSequenceErrorFunction>;
using VelocityMagnitudeSequenceErrorFunction_w =
    ::std::weak_ptr<VelocityMagnitudeSequenceErrorFunction>;
using VelocityMagnitudeSequenceErrorFunction_const_p =
    ::std::shared_ptr<const VelocityMagnitudeSequenceErrorFunction>;
using VelocityMagnitudeSequenceErrorFunction_const_u =
    ::std::unique_ptr<const VelocityMagnitudeSequenceErrorFunction>;
using VelocityMagnitudeSequenceErrorFunction_const_w =
    ::std::weak_ptr<const VelocityMagnitudeSequenceErrorFunction>;

using VelocityMagnitudeSequenceErrorFunctiond_p =
    ::std::shared_ptr<VelocityMagnitudeSequenceErrorFunctiond>;
using VelocityMagnitudeSequenceErrorFunctiond_u =
    ::std::unique_ptr<VelocityMagnitudeSequenceErrorFunctiond>;
using VelocityMagnitudeSequenceErrorFunctiond_w =
    ::std::weak_ptr<VelocityMagnitudeSequenceErrorFunctiond>;
using VelocityMagnitudeSequenceErrorFunctiond_const_p =
    ::std::shared_ptr<const VelocityMagnitudeSequenceErrorFunctiond>;
using VelocityMagnitudeSequenceErrorFunctiond_const_u =
    ::std::unique_ptr<const VelocityMagnitudeSequenceErrorFunctiond>;
using VelocityMagnitudeSequenceErrorFunctiond_const_w =
    ::std::weak_ptr<const VelocityMagnitudeSequenceErrorFunctiond>;

template <typename T>
class VertexSequenceErrorFunctionT;
using VertexSequenceErrorFunction = VertexSequenceErrorFunctionT<float>;
using VertexSequenceErrorFunctiond = VertexSequenceErrorFunctionT<double>;

using VertexSequenceErrorFunction_p = ::std::shared_ptr<VertexSequenceErrorFunction>;
using VertexSequenceErrorFunction_u = ::std::unique_ptr<VertexSequenceErrorFunction>;
using VertexSequenceErrorFunction_w = ::std::weak_ptr<VertexSequenceErrorFunction>;
using VertexSequenceErrorFunction_const_p = ::std::shared_ptr<const VertexSequenceErrorFunction>;
using VertexSequenceErrorFunction_const_u = ::std::unique_ptr<const VertexSequenceErrorFunction>;
using VertexSequenceErrorFunction_const_w = ::std::weak_ptr<const VertexSequenceErrorFunction>;

using VertexSequenceErrorFunctiond_p = ::std::shared_ptr<VertexSequenceErrorFunctiond>;
using VertexSequenceErrorFunctiond_u = ::std::unique_ptr<VertexSequenceErrorFunctiond>;
using VertexSequenceErrorFunctiond_w = ::std::weak_ptr<VertexSequenceErrorFunctiond>;
using VertexSequenceErrorFunctiond_const_p = ::std::shared_ptr<const VertexSequenceErrorFunctiond>;
using VertexSequenceErrorFunctiond_const_u = ::std::unique_ptr<const VertexSequenceErrorFunctiond>;
using VertexSequenceErrorFunctiond_const_w = ::std::weak_ptr<const VertexSequenceErrorFunctiond>;

} // namespace momentum
