# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

"""
Skeleton State Utilities
========================

This module provides utilities for working with skeleton states in PyMomentum.

A skeleton state is a compact 8-dimensional representation of a 3D transformation
that encodes translation, rotation, and uniform scale. The 8 components are organized as:

- **Translation (3 components)**: tx, ty, tz - 3D position offset
- **Rotation (4 components)**: rx, ry, rz, rw - quaternion rotation (x, y, z, w)
- **Scale (1 component)**: s - uniform scale factor

This representation is generated by forward kinematics functions like
:func:`pymomentum.geometry.joint_parameters_to_skeleton_state` and represents the
transformation from a local joint space to the world space.

- Creating skeleton states from individual components (:func:`from_translation`,
  :func:`from_quaternion`, :func:`from_scale`)
- Converting between skeleton states and 4x4 transformation matrices
  (:func:`to_matrix`, :func:`from_matrix`)
- Performing transformations and operations (:func:`multiply`, :func:`inverse`,
  :func:`transform_points`)
- Interpolation and blending (:func:`slerp`, :func:`blend`)
- Validation and manipulation (:func:`check`, :func:`split`)

Example:
    Creating and using a skeleton state::

        import torch
        from pymomentum import skel_state

        # Create identity transform
        identity = skel_state.identity()

        # Create from translation
        translation = torch.tensor([1.0, 2.0, 3.0])
        state = skel_state.from_translation(translation)

        # Transform points
        points = torch.tensor([[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]])
        transformed = skel_state.transform_points(state, points)

Note:
    All functions in this module expect skeleton states to be PyTorch tensors
    with the last dimension having size 8, following the (tx, ty, tz, rx, ry, rz, rw, s)
    format.
"""

from typing import Sequence

import torch
from pymomentum.backend import skel_state_torch
from pymomentum.backend.selection import resolve_backend

# pyre-strict


def check(skel_state: torch.Tensor) -> None:
    """
    Check if the skeleton state has the correct shape.

    :parameter skel_state: The skeleton state to check.
    :type skel_state: torch.Tensor
    :raises ValueError: If the skeleton state does not have the correct shape.
    """
    return skel_state_torch.check(skel_state)


def split(skel_state: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    Split a skeleton state into translation, rotation, and scale components.

    :parameter skel_state: The skeleton state to split.
    :type skel_state: torch.Tensor
    :return: A tuple of tensors (translation, rotation, scale).
    :rtype: tuple[torch.Tensor, torch.Tensor, torch.Tensor]
    """
    return skel_state_torch.split(skel_state)


def from_translation(translation: torch.Tensor) -> torch.Tensor:
    """
    Create a skeleton state from translation.

    :parameter translation: The translation component.
    :type translation: torch.Tensor
    :return: The skeleton state.
    :rtype: torch.Tensor
    """
    return skel_state_torch.from_translation(translation)


def from_quaternion(rotation: torch.Tensor) -> torch.Tensor:
    """
    Create a skeleton state from rotation.

    :parameter rotation: The rotation component.
    :type rotation: torch.Tensor
    :return: The skeleton state.
    :rtype: torch.Tensor
    """
    return skel_state_torch.from_quaternion(rotation)


def from_scale(scale: torch.Tensor) -> torch.Tensor:
    """
    Create a skeleton state from scale.

    :parameter scale: The scale component.
    :type scale: torch.Tensor
    :return: The skeleton state.
    :rtype: torch.Tensor
    """
    return skel_state_torch.from_scale(scale)


def to_matrix(skeleton_state: torch.Tensor) -> torch.Tensor:
    """
    Convert skeleton state to a tensor of 4x4 matrices. The matrix represents the transform from a local joint space to the world space.

    :parameter skeleton_state: The skeleton state to convert.
    :type skeleton_state: torch.Tensor
    :return: A tensor containing 4x4 matrix transforms.
    :rtype: torch.Tensor
    """
    return skel_state_torch.to_matrix(skeleton_state)


def _normalize_split_skel_state(
    components: tuple[torch.Tensor, torch.Tensor, torch.Tensor],
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    Normalize the quaternion component of a split skeleton state.

    :parameter components: Tuple of (translation, rotation, scale) components.
    :type components: tuple[torch.Tensor, torch.Tensor, torch.Tensor]
    :return: Tuple of (translation, normalized_rotation, scale) components.
    :rtype: tuple[torch.Tensor, torch.Tensor, torch.Tensor]
    """
    return skel_state_torch._normalize_split_skel_state(components)


def _multiply_split_skel_states(
    skel_state1: tuple[torch.Tensor, torch.Tensor, torch.Tensor],
    skel_state2: tuple[torch.Tensor, torch.Tensor, torch.Tensor],
) -> torch.Tensor:
    """
    Helper function to multiply two skeleton states from their split components.
    Assumes quaternions are already normalized.

    :parameter skel_state1: Tuple of (translation, rotation, scale) for first skeleton state.
    :type skel_state1: tuple[torch.Tensor, torch.Tensor, torch.Tensor]
    :parameter skel_state2: Tuple of (translation, rotation, scale) for second skeleton state.
    :type skel_state2: tuple[torch.Tensor, torch.Tensor, torch.Tensor]
    :return: The product of the two skeleton states.
    :rtype: torch.Tensor
    """
    return skel_state_torch._multiply_split_skel_states(skel_state1, skel_state2)


@torch.jit.ignore
def _multiply_triton(
    s1: torch.Tensor,
    s2: torch.Tensor,
    assume_normalized: bool,
) -> torch.Tensor:
    from pymomentum.backend import triton_skel_state

    if assume_normalized:
        return triton_skel_state.multiply_assume_normalized(s1, s2)
    return triton_skel_state.multiply(s1, s2)


@torch.jit.ignore
def _inverse_triton(skeleton_states: torch.Tensor) -> torch.Tensor:
    from pymomentum.backend import triton_skel_state

    return triton_skel_state.inverse(skeleton_states)


def multiply(
    s1: torch.Tensor, s2: torch.Tensor, backend: str = "torch"
) -> torch.Tensor:
    """
    Multiply two skeleton states.

    :parameter s1: The first skeleton state.
    :type s1: torch.Tensor
    :parameter s2: The second skeleton state.
    :type s2: torch.Tensor
    :parameter backend: Backend to use. "auto" opts into the experimental Triton backend on CUDA float32, else torch.
    :type backend: str
    :return: The product of the two skeleton states.
    :rtype: torch.Tensor
    """
    backend = resolve_backend(
        backend,
        s2,
        use_double_precision=s1.dtype == torch.float64 or s2.dtype == torch.float64,
    )
    if backend == "triton":
        return _multiply_triton(s1, s2, assume_normalized=False)
    if backend != "torch":
        raise ValueError(f"Unsupported skel_state backend: {backend}")

    return skel_state_torch.multiply(s1, s2)


def multiply_assume_normalized(
    s1: torch.Tensor, s2: torch.Tensor, backend: str = "torch"
) -> torch.Tensor:
    """
    Multiply two skeleton states.
    This is an optimized version that assumes both skeleton states are already properly
    formatted and the quaternions are normalized, skipping validation checks.

    :parameter s1: The first skeleton state.
    :type s1: torch.Tensor
    :parameter s2: The second skeleton state.
    :type s2: torch.Tensor
    :parameter backend: Backend to use. "auto" opts into the experimental Triton backend on CUDA float32, else torch.
    :type backend: str
    :return: The product of the two skeleton states.
    :rtype: torch.Tensor
    """
    backend = resolve_backend(
        backend,
        s2,
        use_double_precision=s1.dtype == torch.float64 or s2.dtype == torch.float64,
    )
    if backend == "triton":
        return _multiply_triton(s1, s2, assume_normalized=True)
    if backend != "torch":
        raise ValueError(f"Unsupported skel_state backend: {backend}")

    return skel_state_torch.multiply_assume_normalized(s1, s2)


def inverse(skeleton_states: torch.Tensor, backend: str = "torch") -> torch.Tensor:
    """
    Compute the inverse of a skeleton state.

    :parameter skeleton_states: The skeleton state to invert.
    :type skeleton_states: torch.Tensor
    :parameter backend: Backend to use. "auto" opts into the experimental Triton backend on CUDA float32, else torch.
    :type backend: str
    :return: The inverted skeleton state.
    :rtype: torch.Tensor
    """
    backend = resolve_backend(
        backend,
        skeleton_states,
        use_double_precision=skeleton_states.dtype == torch.float64,
    )
    if backend == "triton":
        return _inverse_triton(skeleton_states)
    if backend != "torch":
        raise ValueError(f"Unsupported skel_state backend: {backend}")

    return skel_state_torch.inverse(skeleton_states)


def _transform_points_split_skel_state(
    skel_state: tuple[torch.Tensor, torch.Tensor, torch.Tensor],
    points: torch.Tensor,
) -> torch.Tensor:
    """
    Helper function to transform points using skeleton state components.
    Assumes quaternion is already normalized.

    :parameter skel_state: Tuple of (translation, rotation, scale) components.
    :type skel_state: tuple[torch.Tensor, torch.Tensor, torch.Tensor]
    :parameter points: The points to transform.
    :type points: torch.Tensor
    :return: The transformed points.
    :rtype: torch.Tensor
    """
    return skel_state_torch._transform_points_split_skel_state(skel_state, points)


def transform_points(skel_state: torch.Tensor, points: torch.Tensor) -> torch.Tensor:
    """
    Transform 3d points by the transform represented by the skeleton state.

    :parameter skel_state: The skeleton state to use for transformation.
    :type skel_state: torch.Tensor
    :parameter points: The points to transform.
    :type points: torch.Tensor
    :return: The transformed points.
    :rtype: torch.Tensor
    """
    return skel_state_torch.transform_points(skel_state, points)


def transform_points_assume_normalized(
    skel_state: torch.Tensor, points: torch.Tensor
) -> torch.Tensor:
    """
    Transform 3d points by the transform represented by the skeleton state.
    This is an optimized version that assumes the skeleton state is already properly
    formatted and the quaternion is normalized, skipping validation checks.

    :parameter skel_state: The skeleton state to use for transformation.
    :type skel_state: torch.Tensor
    :parameter points: The points to transform.
    :type points: torch.Tensor
    :return: The transformed points.
    :rtype: torch.Tensor
    """
    return skel_state_torch.transform_points_assume_normalized(skel_state, points)


def identity(
    size: Sequence[int] | None = None, device: torch.device | None = None
) -> torch.Tensor:
    """
    Returns a skeleton state representing the identity transform.

    :parameter size: The size of each dimension in the output tensor. Defaults to None, which means the output will be a 1D tensor with 8 elements.
    :type size: list[int], optional
    :parameter device: The device on which to create the tensor. Defaults to None, which means the tensor will be created on the default device.
    :type device: torch.device, optional
    :return: The identity skeleton state.
    :rtype: torch.Tensor
    """
    return skel_state_torch.identity(size=size, device=device)


def blend(
    skel_states: torch.Tensor, weights: torch.Tensor | None = None
) -> torch.Tensor:
    """
    Blend k skeleton states with the passed-in weights.

    :parameter skel_states: The skeleton states to blend.
    :type skel_states: torch.Tensor
    :parameter weights: The weights to use, if not provided, weights are assumed to be all 1s
    :return: The blended skeleton state.
    """
    return skel_state_torch.blend(skel_states, weights)


def slerp(s0: torch.Tensor, s1: torch.Tensor, t: torch.Tensor) -> torch.Tensor:
    """
    Spherical linear interpolation between two skeleton states.

    :parameter s0: The first skeleton state.
    :parameter s1: The second skeleton state.
    :parameter t: The interpolation factor, where 0 <= t <= 1.  t=0 corresponds to s0, t=1 corresponds to s1.
    :return: The interpolated skeleton state.
    """
    return skel_state_torch.slerp(s0, s1, t)


def from_matrix(matrices: torch.Tensor) -> torch.Tensor:
    """
    Convert 4x4 matrices to skeleton states.  Assumes that the scale is uniform.

    Args:
        matrices (torch.Tensor): A tensor of 4x4 matrices.

    Returns:
        torch.Tensor: The corresponding skeleton states.
    """
    return skel_state_torch.from_matrix(matrices)


def multiply_backprop(
    state1: torch.Tensor, state2: torch.Tensor, grad_state: torch.Tensor
) -> tuple[torch.Tensor, torch.Tensor]:
    """
    Backpropagate gradients through skeleton state multiplication.

    This function computes the gradients with respect to the two input skeleton states
    given the gradient with respect to the output of skeleton state multiplication.

    The forward formula is (matching the corrected skel_state.multiply):
    - t = t1 + s1 * quaternion.rotate_vector(q1, t2)
    - q = quaternion.multiply(q1, q2)
    - s = s1 * s2

    :parameter state1: The first skeleton state (parent).
    :type state1: torch.Tensor
    :parameter state2: The second skeleton state (child).
    :type state2: torch.Tensor
    :parameter grad_state: The gradient with respect to the output skeleton state.
    :type grad_state: torch.Tensor
    :return: A tuple of (grad_state1, grad_state2) representing gradients with respect
             to the first and second skeleton states respectively.
    :rtype: tuple[torch.Tensor, torch.Tensor]
    """
    return skel_state_torch.multiply_backprop(state1, state2, grad_state)
