name: 'Setup CUDA Toolkit'
description: 'Install CUDA toolkit and configure Conda environment variables for pixi'

inputs:
  cuda-version:
    description: 'CUDA version to install (e.g., 12.9.0)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install CUDA Toolkit (Windows only)
      # Skip Ubuntu due to CUDA 12.9.0 installer bug: boost::filesystem::copy_file error
      # For wheel builds, we only need CONDA_OVERRIDE_CUDA (PyTorch includes CUDA runtime)
      if: runner.os == 'Windows'
      # Using N-Storm fork until https://github.com/Jimver/cuda-toolkit/issues/395 is resolved
      uses: N-Storm/cuda-toolkit@v0.2.28
      with:
        cuda: ${{ inputs.cuda-version }}

    - name: Check CUDA Version (Windows only)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        nvcc --version

    - name: Set Conda environment variables
      shell: bash
      run: |
        CUDA_MAJOR=$(echo ${{ inputs.cuda-version }} | cut -d'.' -f1)
        echo "CONDA_OVERRIDE_CUDA=$CUDA_MAJOR" >> $GITHUB_ENV
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          echo "Skipping CUDA installation on Ubuntu (using mock CUDA $CUDA_MAJOR for pixi)"
        fi
