/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// This file is @generated by gen_fwd.py
// Do not edit this file directly, instead update gen_fwd_input.toml and run:
// buck run @arvr/mode/platform010/opt //arvr/libraries/momentum:gen_fwd

#pragma once

#include <memory>

namespace momentum {

struct SimdAimConstraints;

using SimdAimConstraints_p = ::std::shared_ptr<SimdAimConstraints>;
using SimdAimConstraints_u = ::std::unique_ptr<SimdAimConstraints>;
using SimdAimConstraints_w = ::std::weak_ptr<SimdAimConstraints>;
using SimdAimConstraints_const_p = ::std::shared_ptr<const SimdAimConstraints>;
using SimdAimConstraints_const_u = ::std::unique_ptr<const SimdAimConstraints>;
using SimdAimConstraints_const_w = ::std::weak_ptr<const SimdAimConstraints>;

struct SimdDistanceConstraints;

using SimdDistanceConstraints_p = ::std::shared_ptr<SimdDistanceConstraints>;
using SimdDistanceConstraints_u = ::std::unique_ptr<SimdDistanceConstraints>;
using SimdDistanceConstraints_w = ::std::weak_ptr<SimdDistanceConstraints>;
using SimdDistanceConstraints_const_p = ::std::shared_ptr<const SimdDistanceConstraints>;
using SimdDistanceConstraints_const_u = ::std::unique_ptr<const SimdDistanceConstraints>;
using SimdDistanceConstraints_const_w = ::std::weak_ptr<const SimdDistanceConstraints>;

struct SimdFixedAxisConstraints;

using SimdFixedAxisConstraints_p = ::std::shared_ptr<SimdFixedAxisConstraints>;
using SimdFixedAxisConstraints_u = ::std::unique_ptr<SimdFixedAxisConstraints>;
using SimdFixedAxisConstraints_w = ::std::weak_ptr<SimdFixedAxisConstraints>;
using SimdFixedAxisConstraints_const_p = ::std::shared_ptr<const SimdFixedAxisConstraints>;
using SimdFixedAxisConstraints_const_u = ::std::unique_ptr<const SimdFixedAxisConstraints>;
using SimdFixedAxisConstraints_const_w = ::std::weak_ptr<const SimdFixedAxisConstraints>;

struct SimdJointToJointDistanceConstraints;

using SimdJointToJointDistanceConstraints_p =
    ::std::shared_ptr<SimdJointToJointDistanceConstraints>;
using SimdJointToJointDistanceConstraints_u =
    ::std::unique_ptr<SimdJointToJointDistanceConstraints>;
using SimdJointToJointDistanceConstraints_w = ::std::weak_ptr<SimdJointToJointDistanceConstraints>;
using SimdJointToJointDistanceConstraints_const_p =
    ::std::shared_ptr<const SimdJointToJointDistanceConstraints>;
using SimdJointToJointDistanceConstraints_const_u =
    ::std::unique_ptr<const SimdJointToJointDistanceConstraints>;
using SimdJointToJointDistanceConstraints_const_w =
    ::std::weak_ptr<const SimdJointToJointDistanceConstraints>;

struct SimdNormalConstraints;

using SimdNormalConstraints_p = ::std::shared_ptr<SimdNormalConstraints>;
using SimdNormalConstraints_u = ::std::unique_ptr<SimdNormalConstraints>;
using SimdNormalConstraints_w = ::std::weak_ptr<SimdNormalConstraints>;
using SimdNormalConstraints_const_p = ::std::shared_ptr<const SimdNormalConstraints>;
using SimdNormalConstraints_const_u = ::std::unique_ptr<const SimdNormalConstraints>;
using SimdNormalConstraints_const_w = ::std::weak_ptr<const SimdNormalConstraints>;

struct SimdOrientationConstraints;

using SimdOrientationConstraints_p = ::std::shared_ptr<SimdOrientationConstraints>;
using SimdOrientationConstraints_u = ::std::unique_ptr<SimdOrientationConstraints>;
using SimdOrientationConstraints_w = ::std::weak_ptr<SimdOrientationConstraints>;
using SimdOrientationConstraints_const_p = ::std::shared_ptr<const SimdOrientationConstraints>;
using SimdOrientationConstraints_const_u = ::std::unique_ptr<const SimdOrientationConstraints>;
using SimdOrientationConstraints_const_w = ::std::weak_ptr<const SimdOrientationConstraints>;

struct SimdPlaneConstraints;

using SimdPlaneConstraints_p = ::std::shared_ptr<SimdPlaneConstraints>;
using SimdPlaneConstraints_u = ::std::unique_ptr<SimdPlaneConstraints>;
using SimdPlaneConstraints_w = ::std::weak_ptr<SimdPlaneConstraints>;
using SimdPlaneConstraints_const_p = ::std::shared_ptr<const SimdPlaneConstraints>;
using SimdPlaneConstraints_const_u = ::std::unique_ptr<const SimdPlaneConstraints>;
using SimdPlaneConstraints_const_w = ::std::weak_ptr<const SimdPlaneConstraints>;

struct SimdPositionConstraints;

using SimdPositionConstraints_p = ::std::shared_ptr<SimdPositionConstraints>;
using SimdPositionConstraints_u = ::std::unique_ptr<SimdPositionConstraints>;
using SimdPositionConstraints_w = ::std::weak_ptr<SimdPositionConstraints>;
using SimdPositionConstraints_const_p = ::std::shared_ptr<const SimdPositionConstraints>;
using SimdPositionConstraints_const_u = ::std::unique_ptr<const SimdPositionConstraints>;
using SimdPositionConstraints_const_w = ::std::weak_ptr<const SimdPositionConstraints>;

struct SimdProjectionConstraints;

using SimdProjectionConstraints_p = ::std::shared_ptr<SimdProjectionConstraints>;
using SimdProjectionConstraints_u = ::std::unique_ptr<SimdProjectionConstraints>;
using SimdProjectionConstraints_w = ::std::weak_ptr<SimdProjectionConstraints>;
using SimdProjectionConstraints_const_p = ::std::shared_ptr<const SimdProjectionConstraints>;
using SimdProjectionConstraints_const_u = ::std::unique_ptr<const SimdProjectionConstraints>;
using SimdProjectionConstraints_const_w = ::std::weak_ptr<const SimdProjectionConstraints>;

class SimdAimDistErrorFunction;

using SimdAimDistErrorFunction_p = ::std::shared_ptr<SimdAimDistErrorFunction>;
using SimdAimDistErrorFunction_u = ::std::unique_ptr<SimdAimDistErrorFunction>;
using SimdAimDistErrorFunction_w = ::std::weak_ptr<SimdAimDistErrorFunction>;
using SimdAimDistErrorFunction_const_p = ::std::shared_ptr<const SimdAimDistErrorFunction>;
using SimdAimDistErrorFunction_const_u = ::std::unique_ptr<const SimdAimDistErrorFunction>;
using SimdAimDistErrorFunction_const_w = ::std::weak_ptr<const SimdAimDistErrorFunction>;

class SimdDistanceErrorFunction;

using SimdDistanceErrorFunction_p = ::std::shared_ptr<SimdDistanceErrorFunction>;
using SimdDistanceErrorFunction_u = ::std::unique_ptr<SimdDistanceErrorFunction>;
using SimdDistanceErrorFunction_w = ::std::weak_ptr<SimdDistanceErrorFunction>;
using SimdDistanceErrorFunction_const_p = ::std::shared_ptr<const SimdDistanceErrorFunction>;
using SimdDistanceErrorFunction_const_u = ::std::unique_ptr<const SimdDistanceErrorFunction>;
using SimdDistanceErrorFunction_const_w = ::std::weak_ptr<const SimdDistanceErrorFunction>;

class SimdFixedAxisErrorFunction;

using SimdFixedAxisErrorFunction_p = ::std::shared_ptr<SimdFixedAxisErrorFunction>;
using SimdFixedAxisErrorFunction_u = ::std::unique_ptr<SimdFixedAxisErrorFunction>;
using SimdFixedAxisErrorFunction_w = ::std::weak_ptr<SimdFixedAxisErrorFunction>;
using SimdFixedAxisErrorFunction_const_p = ::std::shared_ptr<const SimdFixedAxisErrorFunction>;
using SimdFixedAxisErrorFunction_const_u = ::std::unique_ptr<const SimdFixedAxisErrorFunction>;
using SimdFixedAxisErrorFunction_const_w = ::std::weak_ptr<const SimdFixedAxisErrorFunction>;

class SimdJointToJointDistanceErrorFunction;

using SimdJointToJointDistanceErrorFunction_p =
    ::std::shared_ptr<SimdJointToJointDistanceErrorFunction>;
using SimdJointToJointDistanceErrorFunction_u =
    ::std::unique_ptr<SimdJointToJointDistanceErrorFunction>;
using SimdJointToJointDistanceErrorFunction_w =
    ::std::weak_ptr<SimdJointToJointDistanceErrorFunction>;
using SimdJointToJointDistanceErrorFunction_const_p =
    ::std::shared_ptr<const SimdJointToJointDistanceErrorFunction>;
using SimdJointToJointDistanceErrorFunction_const_u =
    ::std::unique_ptr<const SimdJointToJointDistanceErrorFunction>;
using SimdJointToJointDistanceErrorFunction_const_w =
    ::std::weak_ptr<const SimdJointToJointDistanceErrorFunction>;

class SimdNormalErrorFunction;

using SimdNormalErrorFunction_p = ::std::shared_ptr<SimdNormalErrorFunction>;
using SimdNormalErrorFunction_u = ::std::unique_ptr<SimdNormalErrorFunction>;
using SimdNormalErrorFunction_w = ::std::weak_ptr<SimdNormalErrorFunction>;
using SimdNormalErrorFunction_const_p = ::std::shared_ptr<const SimdNormalErrorFunction>;
using SimdNormalErrorFunction_const_u = ::std::unique_ptr<const SimdNormalErrorFunction>;
using SimdNormalErrorFunction_const_w = ::std::weak_ptr<const SimdNormalErrorFunction>;

class SimdOrientationErrorFunction;

using SimdOrientationErrorFunction_p = ::std::shared_ptr<SimdOrientationErrorFunction>;
using SimdOrientationErrorFunction_u = ::std::unique_ptr<SimdOrientationErrorFunction>;
using SimdOrientationErrorFunction_w = ::std::weak_ptr<SimdOrientationErrorFunction>;
using SimdOrientationErrorFunction_const_p = ::std::shared_ptr<const SimdOrientationErrorFunction>;
using SimdOrientationErrorFunction_const_u = ::std::unique_ptr<const SimdOrientationErrorFunction>;
using SimdOrientationErrorFunction_const_w = ::std::weak_ptr<const SimdOrientationErrorFunction>;

class SimdPlaneErrorFunction;

using SimdPlaneErrorFunction_p = ::std::shared_ptr<SimdPlaneErrorFunction>;
using SimdPlaneErrorFunction_u = ::std::unique_ptr<SimdPlaneErrorFunction>;
using SimdPlaneErrorFunction_w = ::std::weak_ptr<SimdPlaneErrorFunction>;
using SimdPlaneErrorFunction_const_p = ::std::shared_ptr<const SimdPlaneErrorFunction>;
using SimdPlaneErrorFunction_const_u = ::std::unique_ptr<const SimdPlaneErrorFunction>;
using SimdPlaneErrorFunction_const_w = ::std::weak_ptr<const SimdPlaneErrorFunction>;

class SimdPositionErrorFunction;

using SimdPositionErrorFunction_p = ::std::shared_ptr<SimdPositionErrorFunction>;
using SimdPositionErrorFunction_u = ::std::unique_ptr<SimdPositionErrorFunction>;
using SimdPositionErrorFunction_w = ::std::weak_ptr<SimdPositionErrorFunction>;
using SimdPositionErrorFunction_const_p = ::std::shared_ptr<const SimdPositionErrorFunction>;
using SimdPositionErrorFunction_const_u = ::std::unique_ptr<const SimdPositionErrorFunction>;
using SimdPositionErrorFunction_const_w = ::std::weak_ptr<const SimdPositionErrorFunction>;

class SimdProjectionErrorFunction;

using SimdProjectionErrorFunction_p = ::std::shared_ptr<SimdProjectionErrorFunction>;
using SimdProjectionErrorFunction_u = ::std::unique_ptr<SimdProjectionErrorFunction>;
using SimdProjectionErrorFunction_w = ::std::weak_ptr<SimdProjectionErrorFunction>;
using SimdProjectionErrorFunction_const_p = ::std::shared_ptr<const SimdProjectionErrorFunction>;
using SimdProjectionErrorFunction_const_u = ::std::unique_ptr<const SimdProjectionErrorFunction>;
using SimdProjectionErrorFunction_const_w = ::std::weak_ptr<const SimdProjectionErrorFunction>;

class SimdStateErrorFunction;

using SimdStateErrorFunction_p = ::std::shared_ptr<SimdStateErrorFunction>;
using SimdStateErrorFunction_u = ::std::unique_ptr<SimdStateErrorFunction>;
using SimdStateErrorFunction_w = ::std::weak_ptr<SimdStateErrorFunction>;
using SimdStateErrorFunction_const_p = ::std::shared_ptr<const SimdStateErrorFunction>;
using SimdStateErrorFunction_const_u = ::std::unique_ptr<const SimdStateErrorFunction>;
using SimdStateErrorFunction_const_w = ::std::weak_ptr<const SimdStateErrorFunction>;

template <typename T>
class SimdCollisionErrorFunctionT;
using SimdCollisionErrorFunction = SimdCollisionErrorFunctionT<float>;
using SimdCollisionErrorFunctiond = SimdCollisionErrorFunctionT<double>;

using SimdCollisionErrorFunction_p = ::std::shared_ptr<SimdCollisionErrorFunction>;
using SimdCollisionErrorFunction_u = ::std::unique_ptr<SimdCollisionErrorFunction>;
using SimdCollisionErrorFunction_w = ::std::weak_ptr<SimdCollisionErrorFunction>;
using SimdCollisionErrorFunction_const_p = ::std::shared_ptr<const SimdCollisionErrorFunction>;
using SimdCollisionErrorFunction_const_u = ::std::unique_ptr<const SimdCollisionErrorFunction>;
using SimdCollisionErrorFunction_const_w = ::std::weak_ptr<const SimdCollisionErrorFunction>;

using SimdCollisionErrorFunctiond_p = ::std::shared_ptr<SimdCollisionErrorFunctiond>;
using SimdCollisionErrorFunctiond_u = ::std::unique_ptr<SimdCollisionErrorFunctiond>;
using SimdCollisionErrorFunctiond_w = ::std::weak_ptr<SimdCollisionErrorFunctiond>;
using SimdCollisionErrorFunctiond_const_p = ::std::shared_ptr<const SimdCollisionErrorFunctiond>;
using SimdCollisionErrorFunctiond_const_u = ::std::unique_ptr<const SimdCollisionErrorFunctiond>;
using SimdCollisionErrorFunctiond_const_w = ::std::weak_ptr<const SimdCollisionErrorFunctiond>;

} // namespace momentum
