/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// This file is @generated by gen_fwd.py
// Do not edit this file directly, instead update gen_fwd_input.toml and run:
// buck run @arvr/mode/platform010/opt //arvr/libraries/momentum:gen_fwd

#pragma once

#include <memory>

namespace momentum {

struct GapFillConfig;

using GapFillConfig_p = ::std::shared_ptr<GapFillConfig>;
using GapFillConfig_u = ::std::unique_ptr<GapFillConfig>;
using GapFillConfig_w = ::std::weak_ptr<GapFillConfig>;
using GapFillConfig_const_p = ::std::shared_ptr<const GapFillConfig>;
using GapFillConfig_const_u = ::std::unique_ptr<const GapFillConfig>;
using GapFillConfig_const_w = ::std::weak_ptr<const GapFillConfig>;

struct GloveConfig;

using GloveConfig_p = ::std::shared_ptr<GloveConfig>;
using GloveConfig_u = ::std::unique_ptr<GloveConfig>;
using GloveConfig_w = ::std::weak_ptr<GloveConfig>;
using GloveConfig_const_p = ::std::shared_ptr<const GloveConfig>;
using GloveConfig_const_u = ::std::unique_ptr<const GloveConfig>;
using GloveConfig_const_w = ::std::weak_ptr<const GloveConfig>;

struct GloveOffset;

using GloveOffset_p = ::std::shared_ptr<GloveOffset>;
using GloveOffset_u = ::std::unique_ptr<GloveOffset>;
using GloveOffset_w = ::std::weak_ptr<GloveOffset>;
using GloveOffset_const_p = ::std::shared_ptr<const GloveOffset>;
using GloveOffset_const_u = ::std::unique_ptr<const GloveOffset>;
using GloveOffset_const_w = ::std::weak_ptr<const GloveOffset>;

struct GloveSensorObservation;

using GloveSensorObservation_p = ::std::shared_ptr<GloveSensorObservation>;
using GloveSensorObservation_u = ::std::unique_ptr<GloveSensorObservation>;
using GloveSensorObservation_w = ::std::weak_ptr<GloveSensorObservation>;
using GloveSensorObservation_const_p = ::std::shared_ptr<const GloveSensorObservation>;
using GloveSensorObservation_const_u = ::std::unique_ptr<const GloveSensorObservation>;
using GloveSensorObservation_const_w = ::std::weak_ptr<const GloveSensorObservation>;

} // namespace momentum
