Momentum: momentum::PlaneCollisionErrorFunctionT< T > Class Template Reference
momentum::PlaneCollisionErrorFunctionT< T > Class Template Reference
Penalizes collision between character collision primitives and a fixed plane.
#include <plane_collision_error_function.h>
Classes
struct ActivePlaneCollision
struct PlaneCollisionResult
Public Member Functions
PlaneCollisionErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt, const CollisionGeometry &cg, const Vector3< T > &planeNormal=Vector3< T >::UnitY(), T planeOffset=T(0))
PlaneCollisionErrorFunctionT (const Character &character, const Vector3< T > &planeNormal=Vector3< T >::UnitY(), T planeOffset=T(0))
double getError (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState) final
double getGradient (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Ref< VectorX< T > > gradient) override
double getJacobian (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Ref< MatrixX< T > > jacobian, Ref< VectorX< T > > residual, int &usedRows) override
size_t getJacobianSize () const final
void setPlane (const Vector3< T > &planeNormal, T planeOffset)
const Vector3< T > & getPlaneNormal () const
T getPlaneOffset () const
std::vector< size_t > getCollidingPrimitives () const
std::vector< PlaneCollisionDebugEntryT< T > > getCollisionDebugInfo () const
Query detailed collision state for all currently-colliding primitives.
std::vector< Vector3< T > > getContactPoints (std::span< const JointStateT< T > > states, T contactMargin)
Return world-space primitive surface points at or near the plane for an explicit state.
std::vector< Vector3< T > > getContactPointsByParent (std::span< const JointStateT< T > > states, T contactMargin)
Return one world-space primitive surface point per parent joint at or near the plane.
Public Member Functions inherited from momentum::SkeletonErrorFunctionT< T >
SkeletonErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt)
virtual ~SkeletonErrorFunctionT ()=default
const Skeleton & getSkeleton () const
const ParameterTransform & getParameterTransform () const
virtual const Character * getCharacter () const
For mesh-based error functions, get access to the underlying character.
void setWeight (T w)
T getWeight () const
void setActiveJoints (const VectorX< bool > &aj)
void setEnabledParameters (const ParameterSet &ps)
virtual double getGradient (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::VectorX< T > >)
virtual double getJacobian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >, Eigen::Ref< Eigen::VectorX< T > >, int &usedRows)
virtual void getHessian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >)
virtual double getSolverDerivatives (const ModelParametersT< T > &parameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, const size_t actualParameters, Eigen::MatrixX< T > &hess, Eigen::VectorX< T > &grad)
virtual bool needsMesh () const
Protected Member Functions
void updatePrimitiveList ()
void updateCandidateCollisionState (const SkeletonStateT< T > &state, T contactMargin)
bool mayPrimitiveContactPlane (const SkeletonStateT< T > &state, size_t primitiveIndex, T contactMargin) const
T primitiveParentSpaceBound (size_t primitiveIndex) const
void prepareContactPointQuery (std::span< const JointStateT< T > > states, T contactMargin)
bool checkCollision (size_t primitiveIndex, PlaneCollisionResult &result) const
void updateActiveParentCollisions ()
void accumulateGradientAlongChain (const SkeletonStateT< T > &state, const Vector3< T > &position, const Vector3< T > &direction, T weight, size_t startJoint, Ref< VectorX< T > > gradient, T scaleCorrection=T(0)) const
Accumulate gradient contributions along a joint chain up to the root.
void accumulateJacobianAlongChain (const SkeletonStateT< T > &state, const Vector3< T > &position, const Vector3< T > &direction, T factor, size_t startJoint, Ref< MatrixX< T > > jacobian, int row, T scaleCorrection=T(0)) const
Accumulate Jacobian contributions along a joint chain up to the root.
Protected Attributes
const CollisionGeometry collisionGeometry_
std::vector< size_t > primitiveIndices_
std::vector< size_t > candidatePrimitiveIndices_
std::vector< T > primitiveParentSpaceBounds_
std::vector< ActivePlaneCollision > activeParentCollisions_
CollisionGeometryStateT< T > collisionState_
Vector3< T > planeNormal_
T planeOffset_
Protected Attributes inherited from momentum::SkeletonErrorFunctionT< T >
const Skeleton & skeleton_
const ParameterTransform & parameterTransform_
T weight_
VectorX< bool > activeJointParams_
ParameterSet enabledParameters_
bool useHessian_ {false}
Static Protected Attributes
static constexpr T kCollisionWeight = 5e-3f
Detailed Description
template<typename T>
class momentum::PlaneCollisionErrorFunctionT< T >
Penalizes collision between character collision primitives and a fixed plane.
The plane is represented by planeNormal.dot(x) - planeOffset = 0; the non-penetrating side is planeNormal.dot(x) >= planeOffset. Capsules, ellipsoids, and boxes use the same collision geometry state and support-radius convention as CollisionErrorFunctionT.
Definition at line 40 of file plane_collision_error_function.h.
Constructor & Destructor Documentation
PlaneCollisionErrorFunctionT() [1/2]
template<typename T > momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionErrorFunctionT (const Skeleton & skel, const ParameterTransform & pt, const CollisionGeometry & cg, const Vector3< T > & planeNormal = Vector3<T>::UnitY(), T planeOffset = T(0)) explicit
Definition at line 28 of file plane_collision_error_function.cpp.
References momentum::SkeletonErrorFunctionT< T >::parameterTransform_, momentum::PlaneCollisionErrorFunctionT< T >::setPlane(), momentum::PlaneCollisionErrorFunctionT< T >::updateCandidateCollisionState(), momentum::PlaneCollisionErrorFunctionT< T >::updatePrimitiveList(), and momentum::ParameterTransformT< T >::zero().
PlaneCollisionErrorFunctionT() [2/2]
template<typename T > momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionErrorFunctionT (const Character & character, const Vector3< T > & planeNormal = Vector3<T>::UnitY(), T planeOffset = T(0)) explicit
Definition at line 47 of file plane_collision_error_function.cpp.
Member Function Documentation
accumulateGradientAlongChain()
template<typename T > void momentum::PlaneCollisionErrorFunctionT< T >::accumulateGradientAlongChain (const SkeletonStateT< T > & state, const Vector3< T > & position, const Vector3< T > & direction, T weight, size_t startJoint, Ref< VectorX< T > > gradient, T scaleCorrection = T(0)) const protected
Accumulate gradient contributions along a joint chain up to the root.
scaleCorrection accounts for the primitive support radius changing with uniform scale.
Definition at line 239 of file plane_collision_error_function.cpp.
References momentum::gradient_jointParams_to_modelParams(), and momentum::kInvalidIndex.
accumulateJacobianAlongChain()
template<typename T > void momentum::PlaneCollisionErrorFunctionT< T >::accumulateJacobianAlongChain (const SkeletonStateT< T > & state, const Vector3< T > & position, const Vector3< T > & direction, T factor, size_t startJoint, Ref< MatrixX< T > > jacobian, int row, T scaleCorrection = T(0)) const protected
Accumulate Jacobian contributions along a joint chain up to the root.
scaleCorrection accounts for the primitive support radius changing with uniform scale.
Definition at line 264 of file plane_collision_error_function.cpp.
References jacobian, momentum::jacobian_jointParams_to_modelParams(), and momentum::kInvalidIndex.
checkCollision()
template<typename T > bool momentum::PlaneCollisionErrorFunctionT< T >::checkCollision (size_t primitiveIndex, PlaneCollisionResult & result) const protected
Definition at line 148 of file plane_collision_error_function.cpp.
References momentum::centeredPrimitiveRadiusAlongDirection(), momentum::Ellipsoid, momentum::isCenteredPrimitive(), MT_THROW, momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::overlap, momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::position, momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::radius, momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::signedDistance, and momentum::TaperedCapsule.
getCollidingPrimitives()
template<typename T > std::vector< size_t > momentum::PlaneCollisionErrorFunctionT< T >::getCollidingPrimitives () const
Definition at line 290 of file plane_collision_error_function.cpp.
getCollisionDebugInfo()
template<typename T > std::vector< PlaneCollisionDebugEntryT< T > > momentum::PlaneCollisionErrorFunctionT< T >::getCollisionDebugInfo () const
Query detailed collision state for all currently-colliding primitives.
Uses the collision state from the most recent solver iteration (computed during getJacobian/getError/getGradient), or the rest pose state immediately after construction.
Definition at line 302 of file plane_collision_error_function.cpp.
References momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::overlap, momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::position, momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::radius, and momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::signedDistance.
getContactPoints()
template<typename T > std::vector< Vector3< T > > momentum::PlaneCollisionErrorFunctionT< T >::getContactPoints (std::span< const JointStateT< T > > states, T contactMargin)
Return world-space primitive surface points at or near the plane for an explicit state.
A primitive contributes when its signed surface distance to the plane is <= contactMargin. The returned point is on the primitive surface, deepest toward the plane.
Definition at line 343 of file plane_collision_error_function.cpp.
References momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::position, momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::radius, and momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::signedDistance.
getContactPointsByParent()
template<typename T > std::vector< Vector3< T > > momentum::PlaneCollisionErrorFunctionT< T >::getContactPointsByParent (std::span< const JointStateT< T > > states, T contactMargin)
Return one world-space primitive surface point per parent joint at or near the plane.
A primitive contributes when its signed surface distance to the plane is <= contactMargin. When multiple primitives under the same parent joint contribute, the returned point is the deepest one toward the plane.
Definition at line 361 of file plane_collision_error_function.cpp.
References momentum::kInvalidIndex, parent, momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::position, momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::radius, and momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::signedDistance.
getError()
template<typename T > double momentum::PlaneCollisionErrorFunctionT< T >::getError (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 405 of file plane_collision_error_function.cpp.
References collision, error, momentum::kParametersPerJoint, MT_CHECK, MT_LOGD, and momentum::sqr().
getGradient()
template<typename T > double momentum::PlaneCollisionErrorFunctionT< T >::getGradient (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Ref< VectorX< T > > gradient) override
Definition at line 437 of file plane_collision_error_function.cpp.
References collision, error, momentum::kParametersPerJoint, MT_CHECK, momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::overlap, momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::position, momentum::sqr(), and wgt.
getJacobian()
template<typename T > double momentum::PlaneCollisionErrorFunctionT< T >::getJacobian (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Ref< MatrixX< T > > jacobian, Ref< VectorX< T > > residual, int & usedRows) override
Definition at line 473 of file plane_collision_error_function.cpp.
References collision, error, jacobian, momentum::kParametersPerJoint, MT_CHECK, MT_PROFILE_FUNCTION, momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::overlap, momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::position, residual, momentum::sqr(), usedRows, and wgt.
getJacobianSize()
template<typename T > size_t momentum::PlaneCollisionErrorFunctionT< T >::getJacobianSize () const final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 530 of file plane_collision_error_function.cpp.
getPlaneNormal()
template<typename T > const Vector3< T > & momentum::PlaneCollisionErrorFunctionT< T >::getPlaneNormal () const inline
Definition at line 77 of file plane_collision_error_function.h.
References momentum::PlaneCollisionErrorFunctionT< T >::planeNormal_.
getPlaneOffset()
template<typename T > T momentum::PlaneCollisionErrorFunctionT< T >::getPlaneOffset () const inline
Definition at line 81 of file plane_collision_error_function.h.
References momentum::PlaneCollisionErrorFunctionT< T >::planeOffset_.
mayPrimitiveContactPlane()
template<typename T > bool momentum::PlaneCollisionErrorFunctionT< T >::mayPrimitiveContactPlane (const SkeletonStateT< T > & state, size_t primitiveIndex, T contactMargin) const protected
Definition at line 116 of file plane_collision_error_function.cpp.
prepareContactPointQuery()
template<typename T > void momentum::PlaneCollisionErrorFunctionT< T >::prepareContactPointQuery (std::span< const JointStateT< T > > states, T contactMargin) protected
Definition at line 321 of file plane_collision_error_function.cpp.
References MT_THROW_IF, and parent.
primitiveParentSpaceBound()
template<typename T > T momentum::PlaneCollisionErrorFunctionT< T >::primitiveParentSpaceBound (size_t primitiveIndex) const protected
Definition at line 74 of file plane_collision_error_function.cpp.
References momentum::Box, momentum::Ellipsoid, MT_THROW, and momentum::TaperedCapsule.
setPlane()
template<typename T > void momentum::PlaneCollisionErrorFunctionT< T >::setPlane (const Vector3< T > & planeNormal, T planeOffset)
Definition at line 65 of file plane_collision_error_function.cpp.
References MT_CHECK.
Referenced by momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionErrorFunctionT().
updateActiveParentCollisions()
template<typename T > void momentum::PlaneCollisionErrorFunctionT< T >::updateActiveParentCollisions () protected
Definition at line 212 of file plane_collision_error_function.cpp.
References collision, momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::overlap, and parent.
updateCandidateCollisionState()
template<typename T > void momentum::PlaneCollisionErrorFunctionT< T >::updateCandidateCollisionState (const SkeletonStateT< T > & state, T contactMargin) protected
Definition at line 129 of file plane_collision_error_function.cpp.
References MT_PROFILE_EVENT.
Referenced by momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionErrorFunctionT().
updatePrimitiveList()
template<typename T > void momentum::PlaneCollisionErrorFunctionT< T >::updatePrimitiveList () protected
Definition at line 100 of file plane_collision_error_function.cpp.
References momentum::kInvalidIndex, and parent.
Referenced by momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionErrorFunctionT().
Member Data Documentation
activeParentCollisions_
template<typename T > std::vector<ActivePlaneCollision> momentum::PlaneCollisionErrorFunctionT< T >::activeParentCollisions_ protected
Definition at line 169 of file plane_collision_error_function.h.
candidatePrimitiveIndices_
template<typename T > std::vector<size_t> momentum::PlaneCollisionErrorFunctionT< T >::candidatePrimitiveIndices_ protected
Definition at line 167 of file plane_collision_error_function.h.
collisionGeometry_
template<typename T > const CollisionGeometry momentum::PlaneCollisionErrorFunctionT< T >::collisionGeometry_ protected
Definition at line 165 of file plane_collision_error_function.h.
collisionState_
template<typename T > CollisionGeometryStateT<T> momentum::PlaneCollisionErrorFunctionT< T >::collisionState_ protected
Definition at line 170 of file plane_collision_error_function.h.
kCollisionWeight
template<typename T > constexpr T momentum::PlaneCollisionErrorFunctionT< T >::kCollisionWeight = 5e-3f static constexpr protected
Definition at line 174 of file plane_collision_error_function.h.
planeNormal_
template<typename T > Vector3<T> momentum::PlaneCollisionErrorFunctionT< T >::planeNormal_ protected
Definition at line 171 of file plane_collision_error_function.h.
Referenced by momentum::PlaneCollisionErrorFunctionT< T >::getPlaneNormal().
planeOffset_
template<typename T > T momentum::PlaneCollisionErrorFunctionT< T >::planeOffset_ protected
Definition at line 172 of file plane_collision_error_function.h.
Referenced by momentum::PlaneCollisionErrorFunctionT< T >::getPlaneOffset().
primitiveIndices_
template<typename T > std::vector<size_t> momentum::PlaneCollisionErrorFunctionT< T >::primitiveIndices_ protected
Definition at line 166 of file plane_collision_error_function.h.
primitiveParentSpaceBounds_
template<typename T > std::vector<T> momentum::PlaneCollisionErrorFunctionT< T >::primitiveParentSpaceBounds_ protected
Definition at line 168 of file plane_collision_error_function.h.
The documentation for this class was generated from the following files:
character_solver/fwd.h
character_solver/plane_collision_error_function.h
character_solver/plane_collision_error_function.cpp