Momentum: momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult Struct Reference
momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult Struct Reference
#include <plane_collision_error_function.h>
Public Attributes
T signedDistance = T(0)
T radius = T(0)
T overlap = T(0)
Vector3< T > position = Vector3<T>::Zero()
Detailed Description
template<typename T>
struct momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult
Definition at line 111 of file plane_collision_error_function.h.
Member Data Documentation
overlap
template<typename T > T momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::overlap = T(0)
Definition at line 114 of file plane_collision_error_function.h.
Referenced by momentum::PlaneCollisionErrorFunctionT< T >::checkCollision(), momentum::PlaneCollisionErrorFunctionT< T >::getCollisionDebugInfo(), momentum::PlaneCollisionErrorFunctionT< T >::getGradient(), momentum::PlaneCollisionErrorFunctionT< T >::getJacobian(), and momentum::PlaneCollisionErrorFunctionT< T >::updateActiveParentCollisions().
position
template<typename T > Vector3<T> momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::position = Vector3<T>::Zero()
Definition at line 115 of file plane_collision_error_function.h.
Referenced by momentum::PlaneCollisionErrorFunctionT< T >::checkCollision(), momentum::PlaneCollisionErrorFunctionT< T >::getCollisionDebugInfo(), momentum::PlaneCollisionErrorFunctionT< T >::getContactPoints(), momentum::PlaneCollisionErrorFunctionT< T >::getContactPointsByParent(), momentum::PlaneCollisionErrorFunctionT< T >::getGradient(), and momentum::PlaneCollisionErrorFunctionT< T >::getJacobian().
radius
template<typename T > T momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::radius = T(0)
Definition at line 113 of file plane_collision_error_function.h.
Referenced by momentum::PlaneCollisionErrorFunctionT< T >::checkCollision(), momentum::PlaneCollisionErrorFunctionT< T >::getCollisionDebugInfo(), momentum::PlaneCollisionErrorFunctionT< T >::getContactPoints(), and momentum::PlaneCollisionErrorFunctionT< T >::getContactPointsByParent().
signedDistance
template<typename T > T momentum::PlaneCollisionErrorFunctionT< T >::PlaneCollisionResult::signedDistance = T(0)
Definition at line 112 of file plane_collision_error_function.h.
Referenced by momentum::PlaneCollisionErrorFunctionT< T >::checkCollision(), momentum::PlaneCollisionErrorFunctionT< T >::getCollisionDebugInfo(), momentum::PlaneCollisionErrorFunctionT< T >::getContactPoints(), and momentum::PlaneCollisionErrorFunctionT< T >::getContactPointsByParent().
The documentation for this struct was generated from the following file:
character_solver/plane_collision_error_function.h