Momentum: momentum::PlaneCollisionQueryT< T >::Result Struct Reference
momentum::PlaneCollisionQueryT< T >::Result Struct Reference
Collision information for one primitive selected by the current query state.
#include <plane_collision_query.h>
Public Member Functions
T surfaceDistance () const
Signed distance from the primitive surface point to the plane.
Public Attributes
size_t primitiveIndex = kInvalidIndex
size_t parentJoint = kInvalidIndex
T signedDistance = T(0)
T radius = T(0)
T overlap = T(0)
Vector3< T > position = Vector3<T>::Zero()
Detailed Description
template<typename T>
struct momentum::PlaneCollisionQueryT< T >::Result
Collision information for one primitive selected by the current query state.
Definition at line 57 of file plane_collision_query.h.
Member Function Documentation
surfaceDistance()
template<typename T > T momentum::PlaneCollisionQueryT< T >::Result::surfaceDistance () const inline
Signed distance from the primitive surface point to the plane.
Definition at line 66 of file plane_collision_query.h.
References momentum::PlaneCollisionQueryT< T >::Result::radius, and momentum::PlaneCollisionQueryT< T >::Result::signedDistance.
Referenced by momentum::PlaneCollisionQueryT< T >::getContactPoints(), and momentum::PlaneCollisionQueryT< T >::getContactPointsByParentWithDetails().
Member Data Documentation
overlap
template<typename T > T momentum::PlaneCollisionQueryT< T >::Result::overlap = T(0)
Definition at line 62 of file plane_collision_query.h.
Referenced by momentum::PlaneCollisionQueryT< T >::getCollisionDebugInfo(), and momentum::PlaneCollisionQueryT< T >::updateActiveParentCollisions().
parentJoint
template<typename T > size_t momentum::PlaneCollisionQueryT< T >::Result::parentJoint = kInvalidIndex
Definition at line 59 of file plane_collision_query.h.
Referenced by momentum::PlaneCollisionQueryT< T >::getCollisionDebugInfo(), momentum::PlaneCollisionQueryT< T >::getContactPointsByParentWithDetails(), and momentum::PlaneCollisionQueryT< T >::updateActiveParentCollisions().
position
template<typename T > Vector3<T> momentum::PlaneCollisionQueryT< T >::Result::position = Vector3<T>::Zero()
Definition at line 63 of file plane_collision_query.h.
Referenced by momentum::PlaneCollisionQueryT< T >::getCollisionDebugInfo(), momentum::PlaneCollisionQueryT< T >::getContactPoints(), and momentum::PlaneCollisionQueryT< T >::getContactPointsByParentWithDetails().
primitiveIndex
template<typename T > size_t momentum::PlaneCollisionQueryT< T >::Result::primitiveIndex = kInvalidIndex
Definition at line 58 of file plane_collision_query.h.
Referenced by momentum::PlaneCollisionQueryT< T >::getCollisionDebugInfo().
radius
template<typename T > T momentum::PlaneCollisionQueryT< T >::Result::radius = T(0)
Definition at line 61 of file plane_collision_query.h.
Referenced by momentum::PlaneCollisionQueryT< T >::getCollisionDebugInfo(), and momentum::PlaneCollisionQueryT< T >::Result::surfaceDistance().
signedDistance
template<typename T > T momentum::PlaneCollisionQueryT< T >::Result::signedDistance = T(0)
Definition at line 60 of file plane_collision_query.h.
Referenced by momentum::PlaneCollisionQueryT< T >::getCollisionDebugInfo(), and momentum::PlaneCollisionQueryT< T >::Result::surfaceDistance().
The documentation for this struct was generated from the following file:
character_solver/plane_collision_query.h