name: Publish to GHE

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Push Mirror to GitHub Enterprise
        run: |
          git checkout main
          git push https://${{ secrets.GHE_USERNAME }}:${{ secrets.INTERNAL_GHE_TOKEN }}@${{ secrets.INTERNAL_GHE_REPO_URL }} main:main --force
          git push https://${{ secrets.GHE_USERNAME }}:${{ secrets.INTERNAL_GHE_TOKEN }}@${{ secrets.INTERNAL_GHE_REPO_URL }} --tags
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
